server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://14.35.68.147:5432/sample
    username: pjys
    password: pjys
  redis:
    host: saama.kr
    port: 6379
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    # hibernate: ddl-auto 사용 여부 / 기본값 false
    generate-ddl: true
    hibernate:
      format_sql: true
      #ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  thymeleaf:
    cache: false