spring:
  datasource:
    oracle:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      jdbc-url: jdbc:oracle:thin:@localhost:1521/xe
      username: TEST
      password: test1234
jpa:
  database-platform: org.hibernate.dialect.Oracle10gDialect
  show-sql: true
  hibernate:
    format_sql: true
    ddl-auto: create

